# Generated by Django 6.0.1 on 2026-02-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_resume_file_remove_resume_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='parsed_data',
        ),
    ]
